### ISSUE TITLE
Issue with Vevo video

### ISSUE THREAD

**Issue by hesa2020** [MyToolkit/MyToolkit#24]
Hello, since today the YouTube.GetVideoUriAsync
Get a url but when i browse it with chrome its a blank page and viewing the source return a blank file.

This seems to be happening with Vevo only.

Here is how i use the script: https://github.com/hesa2020/Hesa-Twitch-Bot/blob/master/HESA%20Twitch%20Bot/Managers/MusicManager.cs

Hopefully this will be fixed.
Thanks and i enjoy MyToolKit :D

**Comment by rsuter** [comment]
Original issue: http://mytoolkit.codeplex.com/discussions/476808

**Comment by naweed** [comment]
Same issue with Youtube videos as well.

Thanks. And love this great library.

**Comment by rsuter** [comment]
Will be resolved tomorrow...

**Comment by naweed** [comment]
Thank you buddy.

Just FYI, I love this toolkit. Amazing work.


On Tue, Nov 17, 2015 at 21:53 PM, Rico Suter <notifications@github.com>
wrote:

Will be resolved tomorrow...


—
Reply to this email directly or view it on GitHub
<https://github.com/MyToolkit/MyToolkit/issues/24#issuecomment-157469253>.










-- 
Sent from MetroMail

**Comment by rsuter** [comment]
Fixed in v2.5.6, please check if it is working for you

**Comment by naweed** [comment]
Will check tonight and update you. Thanks.

**Comment by naweed** [comment]
Works like a charm :)

**Comment by naweed** [comment]
Hi, the issue is back again since this morning. It is not working anymore.

**Comment by rsuter** [comment]
Fixed again in v2.5.7

**Comment by naweed** [comment]
Thanks. Is 2.5.7 code checked in? I think the code is still 2.5.6.

**Comment by rsuter** [comment]
Its commited: https://github.com/MyToolkit/MyToolkit/commit/7d886a7d7a855954a325bbb4a0303f6a246e8ce0

**Comment by naweed** [comment]
Thanks. Will check this tonight.

**Comment by naweed** [comment]
Works fine now. Thanks once again.

**Comment by Sivze** [comment]
Problem again with the Vevo Videos!

**Comment by naweed** [comment]
YouTube videos also stopped working.
